spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
custom:
  gen:
    dirPath: c:\temp\sb-k8s-2501-test\gen
  temp:
    dirPath: c:\temp